version: 0.2

phases:
  install:
    commands:
      #install Node 12
    - echo installing node js 16.x...
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
        #install Yarn
      - echo Installling yarn ///
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg |  apt-key add -
      - apt install --no-install-recommends yarn

 pre_build:
    commands:
      #install dependencies
      - echo Installing dependencies...
      - yarn
  build:
    commands:
      #build
      - echo Building.....
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build